### ISSUE TITLE
How are community contributions handled ? 

### ISSUE THREAD

**Issue by brucellino** [astro4dev/OAD-Data-Science-Toolkit#40]
Hi ! 

Great project, I'd love to contribute. It's not clear right now, looking at the repository how that is expected to be done. Have you considered using GitHub's [community health tools](https://github.com/blog/2397-making-it-easier-to-grow-communities-on-github)

**Comment by paultheastronomer** [comment]
Hi @brucellino,

There are several ways which you can contribute which is listed [here](https://datascience.astro4dev.org/index.php#contribute). These are suggestions, but contributions of any sort, are welcome. I have put together a document on [How to upload content](https://github.com/astro4dev/OAD-Data-Science-Toolkit/blob/master/How_to_upload_content.md). You seem well versed in GitHub and might know what works and not. Please feel free to take an active role in improving this project!

**Comment by paultheastronomer** [comment]
How do I implement the health tools? The link you sent seems like a description of features mainly.

**Comment by brucellino** [comment]
Hi @paultheastronomer 
First off, thanks for the invite. I hope I can bring something useful to the org :smile: 

The community health is an API that GitHub exposes, to give some measure of how healthy the community is. It takes inspiration from https://opensource.guide/

Basically, communities need to have clear guidelines on how contributions can be made, what credit is given if any for them, what the expected behaviour is, what makes a good vs not so good contribution etc.

It looks like we've already got a LICENSE and README here, but there is no CONTRIBUTING and CODE_OF_CONDUCT.

This is just a matter of formalising whatever process is already in place "IRL", since in a healthy online commmunity, contributors may never meet each other. (hi !)

If you're the owner of the repo, you should be able to add templates for these things in under the "insights" tab.

**Comment by paultheastronomer** [comment]
Thank you for showing me this @brucellino. I've now added the CONTRIBUTING and CODE_OF_CONDUCT. I will review and add to these files in due course. Thanks!

**Comment by brucellino** [comment]
Woot ! This is  the kind of thing that requires some careful discussion, and should  be done little-by-little, but it's really important for random interested people like me to see how to contribute, and what I'd get out of it  if I did. 

This is an example of a "complicated" one : https://github.com/AAROC/DevOps/blob/master/CONTRIBUTING.md
whilst https://github.com/AAROC/CODE-RADE-container/blob/master/CONTRIBUTING.md is the "super-short" version.

**Comment by paultheastronomer** [comment]
I think I will focus on this section over the next few days. As a starting point I have now added the content from the old 'How to file' into CONTRIBUTING. Thanks for showing me all this. I am eager to keep learning!

**Comment by brucellino** [comment]
Don't thank me, I got all this from https://github.com/mozillascience !
