### ISSUE TITLE
Is the database published  ? 

### ISSUE THREAD

**Issue by brucellino** [astro4dev/OAD-Data-Science-Toolkit#41]
It seems that content is added to a sql db. How can one get access to this in order to test locally ? 

What tests are made to check whether contributions and pull requests are compatible with the db ?. 

Is this described somewhere? 

Thanks ! 
Bruce

**Comment by paultheastronomer** [comment]
The database is available in it's [own repository](https://github.com/astro4dev/toolkit_db). You can download it and use it locally if you like.

There is currently no automatic way of checking if the pull requests are compatible with the db. At the moment our best approach is to download the change locally, test it, then accept the request if no errors are found. More information on how the toolkit works can be found [here](https://github.com/astro4dev/OAD-Data-Science-Toolkit/blob/master/How_the_toolkit_works.md).
