### ISSUE TITLE
Carpentry courses ? 

### ISSUE THREAD

**Issue by brucellino** [astro4dev/OAD-Data-Science-Toolkit#42]
Hi ! 

It seems to me that much of these courses could beneffit from having the students complete a [software carpentry bootcamp](https://software-carpentry.org/lessons/). Particularly the programming and data wrangling side  of things.

Have  you considered interfacing with their pedagogy at all ?

**Comment by paultheastronomer** [comment]
I have not. Do you know them? Might they be interested?

**Comment by brucellino** [comment]
Hi @paultheastronomer ! Thanks for getting back on this.

@jduckles is the guy to talk to overall. There is a very strong carpentry presence in South Africa, including , amongst other @anelda, @fanie-riekert, @confluence, etc.

The carpentry lessons are CC-BY, so one can re-mix them. They have been battle-tested extensively, and are very good for very beginners. I think particularly the [sql](https://github.com/swcarpentry/sql-novice-survey) and [R](https://github.com/datacarpentry/R-ecology-lesson/) courses may be good starting points - but I'm not sure how much has been done here already.

**Comment by jduckles** [comment]
Happy to find a time to chat, please reach out to me at jduckles@carpentries.org if you'd like to find a time.

**Comment by anelda** [comment]
Hi @paultheastronomer, nice to hear about  your activities. We have a growing number of Software and Data Carpentry instructors in South Africa and elsewhere in Africa and have run over 20 workshops in Africa in the last 2 years. You are welcome to contact me if you're interested to learn more or get more involved. We're running another instructor training in October in Potchefstroom which will be open to anyone in Africa. You can also join the African SWC mailing list at https://groups.google.com/forum/#!forum/swc-za if you want to be kept up to date with activities and events. Find me at anelda.vdwalt@gmail.com. Looking forward to hearing from you.

**Comment by paultheastronomer** [comment]
Hi @jduckles, @anelda!

Thank you both for showing interest. I've had a look at some of the materials you curate and they look great! What a wonderful initiative! I can see some of it being quite useful for when content for the toolkit is created. We at the OAD are, however, primarily interested in topics which have an astronomy element to them. I think that if people want a basic primer into R or SQL then your repositories are great and I see no need to copy them. However, if for example somebody is writing an astronomy lesson which uses SQL, then your resources will be very handy.

As for participating, I will sadly not be staying in South Africa beyond the month of August. :(
