### ISSUE TITLE
Continuous Integration ? 

### ISSUE THREAD

**Issue by brucellino** [astro4dev/OAD-Data-Science-Toolkit#43]
Would there be an interest in providing a short course on continuous integration and testing of software ?

**Comment by paultheastronomer** [comment]
I am certainly interested. +1 Is this something you were thinking you could contribute with?

**Comment by brucellino** [comment]
All day and all night :smile: An example of what we're doing for application delivery is at https://ci.sagrid.ac.za (part of the the [CODE-RADE project](https://github.com/AAROC/CODE-RADE) which builds what you see here  : http://www.africa-grid.org/applications/

CI can be useful in teaching, to give feedback to students quickly, in a somewhat unbiased way (ie, a "check-my-working" service). We used it quite a bit during the [Sci-GaIA](http://www.sci-gaia.eu) hackfests - https://github.com/AAROC/e-Research-Hackfest-prep

I'm trying to figure out where the lessons are - when I get there, my plan is to go through them myself and see how to contribute, but if you or @astro4dev have any ideas, I'd be happy to see about implementing them.

**Comment by paultheastronomer** [comment]
Excellent!

I will try and have the _how to contribute_ file ready ASAP. You are welcome to add folders etc.. as you wish. The toolkit repo is hierarchical, but the web interface I'm developing is not. It uses relational databases so that we can move away from being forced to put things in categories.

**Comment by paultheastronomer** [comment]
CONTRIBUTING.md file added and edited. Available [here](https://github.com/astro4dev/OAD-Data-Science-Toolkit/blob/master/CONTRIBUTING.md).
