### ISSUE TITLE
Supervised Learning dataset is not CSV

### ISSUE THREAD

**Issue by brucellino** [astro4dev/OAD-Data-Science-Toolkit#45]
The example for the supervised learning dataset seems to aspire to be CSV (from the file suffix), but is not: 

https://github.com/astro4dev/OAD-Data-Science-Toolkit/blob/master/Teaching%20Materials/Machine%20Learning/Supervised%20Learning/Examples/PPC/Data/pulsar.csv

It is an html file.

This looks like a curl was done without auth token. 

Perhaps someone could fix it ?

**Comment by paultheastronomer** [comment]
Contacted author who has no time to contribute at this stage. @scienceguyrob hopes to find time to do it at a later stage. Perhaps we should remove it if it does not work?

**Comment by as595** [comment]
Hi Paul - I found this issue and went and remade the file. I don't have push access though (and it won't let me attach a csv here...). You can get it from: https://github.com/as595/NITheP/blob/master/TUTORIALS/data/pulsar.csv

**Comment by paultheastronomer** [comment]
Thank you @as595. I've now added the file.
